#!/usr/bin/env bash
# ============================================================
# PiBoard - install/enable-poweroff.sh
# Accorde au service PiBoard le droit d'eteindre la machine (menu
# « Quitter » > « Eteindre »), et rien d'autre.
#
# Pourquoi un script a part : les mises a jour de PiBoard (automatiques
# ou par ZIP) tournent sans privileges et ne touchent jamais /etc. Un Pi
# installe avant la 1.104.0 puis mis a jour n'a donc jamais recu cette
# permission. Ce script la pose sans relancer toute l'installation.
# install.sh l'appelle aussi : une seule source pour la regle.
#
# Pourquoi polkit et pas sudo : le service declare NoNewPrivileges=true,
# qui neutralise sudo (binaire setuid). L'extinction passe par
# systemd-logind (D-Bus), dont polkit garde l'entree.
#
# Grants the PiBoard service the right to power the machine off, and
# nothing else. PiBoard updates run unprivileged and never touch /etc,
# so a Pi installed before 1.104.0 then updated never got it: this
# script sets it without re-running the whole install. install.sh calls
# it too (single source). Polkit rather than sudo: the service has
# NoNewPrivileges=true, which neutralises sudo.
#
# Usage :
#   sudo bash install/enable-poweroff.sh [utilisateur] [--other-sessions] [--ignore-inhibit]
#     utilisateur        utilisateur du service (defaut : celui de
#                        piboard.service, sinon $SUDO_USER)
#     --other-sessions   autorise aussi l'extinction quand un AUTRE
#                        utilisateur a une session ouverte (SSH...)
#     --ignore-inhibit   autorise aussi a passer outre un programme qui
#                        bloque l'extinction
# ============================================================
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Merci de lancer ce script avec sudo. / Please run this script with sudo." >&2
  exit 1
fi

TARGET_USER=""
EXTRA=()
for arg in "$@"; do
  case "$arg" in
    --other-sessions) EXTRA+=("org.freedesktop.login1.power-off-multiple-sessions") ;;
    --ignore-inhibit) EXTRA+=("org.freedesktop.login1.power-off-ignore-inhibit") ;;
    -*) echo "Option inconnue / unknown option: $arg" >&2; exit 1 ;;
    *) TARGET_USER="$arg" ;;
  esac
done

if [[ -z "$TARGET_USER" ]]; then
  TARGET_USER="$(systemctl show piboard.service -p User --value 2>/dev/null || true)"
fi
if [[ -z "$TARGET_USER" ]]; then
  TARGET_USER="${SUDO_USER:-pi}"
fi
if ! id "$TARGET_USER" >/dev/null 2>&1; then
  echo "Utilisateur introuvable / user not found: $TARGET_USER" >&2
  exit 1
fi

if [[ ! -d /etc/polkit-1/rules.d ]]; then
  echo "polkit absent : l'extinction depuis PiBoard n'est pas disponible." >&2
  echo "polkit missing: powering off from PiBoard is not available." >&2
  exit 1
fi

ACTIONS='action.id == "org.freedesktop.login1.power-off"'
for a in "${EXTRA[@]}"; do
  ACTIONS="$ACTIONS ||
       action.id == \"$a\""
done

RULE=/etc/polkit-1/rules.d/50-piboard-poweroff.rules
cat > "$RULE" <<POLKIT
// Genere par install/enable-poweroff.sh de PiBoard. Autorise
// l'utilisateur du service a eteindre la machine, et rien d'autre.
// Generated by PiBoard's install/enable-poweroff.sh. Allows the service
// user to power the machine off, and nothing else.
polkit.addRule(function(action, subject) {
  if (($ACTIONS) &&
      subject.user == "$TARGET_USER") {
    return polkit.Result.YES;
  }
});
POLKIT
chmod 644 "$RULE"
systemctl reload polkit 2>/dev/null || systemctl restart polkit 2>/dev/null || true

echo "    OK ($RULE, utilisateur / user: $TARGET_USER)"
# Verification immediate, avec l'identite du service.
# Immediate check, as the service user.
if command -v pkcheck >/dev/null 2>&1; then
  # « exec » : pkcheck reprend le PID du shell lance sous l'utilisateur
  # du service, c'est donc bien SON droit qui est teste.
  # "exec": pkcheck takes over the PID of the shell started as the
  # service user, so it is really THAT user's right being checked.
  if sudo -u "$TARGET_USER" bash -c 'exec pkcheck --action-id org.freedesktop.login1.power-off --process $$' >/dev/null 2>&1; then
    echo "    Verifie : $TARGET_USER peut eteindre la machine. / Checked: $TARGET_USER may power off."
  else
    echo "    Attention : polkit ne confirme pas encore la permission (redemarrez polkit ou la machine)." >&2
    echo "    Warning: polkit does not confirm the permission yet (restart polkit or the machine)." >&2
  fi
fi
